// Arc Power — Electron main process entry.
//
// Modes:
//   electron .                -> UI (M2a: design system, Dashboard, OC, Fan)
//   electron . --headless     -> M1 smoke sequence on the real A770, exit 0/1
//   electron . --headless --mock -> smoke against MockBackend (no hardware)
//   electron . --apply-worker <reqFile> <outFile> -> M2C-C elevated
//     self-worker: hidden (no window/tray), never re-elevates, exits after
//     writing the result file. Spawned by the non-elevated app via
//     Start-Process -Verb RunAs (one UAC per apply).
//
// The smoke path constructs the backend with allowAutoWaiver: true — the
// ONLY place product code may do that (developer's own machine, no value
// changes). The normal app path never auto-accepts a waiver; the renderer
// asks the user and calls waiver-accept over IPC.

import { app, BrowserWindow, Tray, Menu, dialog, nativeImage } from 'electron';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createBackend } from './backend/index.js';
import { runSmoke } from './smoke.js';
import { runUiVerify, runFeaturesetVerify, runTweaksApplyVerify } from './ui-verify.js';
import { collectHealth } from './health.js';
import { registerIpc } from './ipc.js';
import { seedWaiverState } from './ipc-core.js';
import { ProfileStore } from './store/profile-store.js';
import { createStartup, createMockStartup } from './startup.js';
import { createDriverInfo, createMockDriverInfo } from './driver-info.js';
import { REGISTRY_CATALOG, createRegistryCatalog, createMockRegistryCatalog, createMockRegistryState } from './registry-catalog.js';
import { createRegistryApply, createMockRegistryApply } from './registry-apply.js';
import { createPresentmonAdapter } from './presentmon/presentmon-client.js';
import { applyProfile, runApplyOnStartup } from './apply-on-boot.js';
import { createTray, buildTrayMenuTemplate, TRAY_LABEL_TOGGLE, trayBalloonForOutcome } from './tray.js';
import { isElevated as isElevatedReal } from './elevation.js';
import { OldIgcl } from './old-igcl.js';
import { executeApply, requiresExtendedRange } from './apply-routing.js';
import { runApplyWorker } from './apply-worker.js';
import { createApplyRunner } from './elevated-apply.js';
import { createMockOldIgcl } from './backend/mock-backend.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const headless = process.argv.includes('--headless');
const uiVerify = process.argv.includes('--ui-verify');
// --ui-verify is dev tooling: it ALWAYS uses the mock backend (never touches
// hardware), so treat it as mock for backend selection.
const mock = process.argv.includes('--mock') || process.env.RID_BACKEND === 'mock' || uiVerify;
const applyProfileIdx = process.argv.indexOf('--apply-profile');
const applyProfileId = applyProfileIdx >= 0 ? process.argv[applyProfileIdx + 1] : null;
// M2C-C apply-worker mode: `--apply-worker <reqFile> <outFile>`.
const applyWorkerIdx = process.argv.indexOf('--apply-worker');
const workerReqFile = applyWorkerIdx >= 0 ? process.argv[applyWorkerIdx + 1] : null;
const workerOutFile = applyWorkerIdx >= 0 ? process.argv[applyWorkerIdx + 2] : null;

function createWindow() {
  const win = new BrowserWindow({
    width: 1280,
    height: 820,
    minWidth: 980,
    minHeight: 640,
    title: 'Arc Power',
    backgroundColor: '#0f1116',
    // M2C-B B6: the blue "AP" logo (generated by scripts/make-icon.js).
    icon: path.join(__dirname, '..', 'assets', 'icon.png'),
    // M2b UX: no visible Electron menu bar (an Alt-key shortcut can reveal
    // it later if ever needed).
    autoHideMenuBar: true,
    webPreferences: {
      contextIsolation: true,
      sandbox: true,
      nodeIntegration: false,
      preload: path.join(__dirname, '..', 'preload.cjs'),
    },
  });
  win.webContents.on('console-message', (event) => {
    // Electron >= 30: the event object carries { level, message, ... }.
    const level = typeof event.level === 'number' ? event.level : 0;
    const message = typeof event.message === 'string' ? event.message : '';
    if (level >= 2) console.error(`[renderer] ${message}`);
  });
  win.loadFile(path.join(__dirname, '..', 'renderer', 'index.html'));
  return win;
}

// --- system tray (normal app path only — never headless) -------------------
// The menu is rebuilt from the persisted active profile at boot; M2b-B can
// rebuild it when the profile changes.
let trayRef = null;
async function setupTray({ getWindow, backend, store, oldIgcl, applyRunner }) {
  const menuTemplate = async () => {
    let hasActiveProfile = false;
    try {
      const settings = await store.loadSettings();
      const profiles = await store.loadProfiles();
      hasActiveProfile = settings.activeProfileId !== null
        && profiles.some((p) => p.id === settings.activeProfileId);
    } catch {
      hasActiveProfile = false;
    }
    return buildTrayMenuTemplate({
      hasActiveProfile,
      onToggle: () => {
        const win = getWindow();
        if (win) {
          if (win.isVisible()) win.hide();
          else { win.show(); win.focus(); }
        }
      },
      onApplyProfile: async () => {
        try {
          const settings = await store.loadSettings();
          const profiles = await store.loadProfiles();
          const profile = profiles.find((p) => p.id === settings.activeProfileId);
          // M2C-C gating: extended-range values (>252 W / >90 C) need the
          // explicit confirm dialog even from the tray (an explicit user
          // action) — the boot path applies its saved profile without one.
          if (profile && requiresExtendedRange(profile.settings)) {
            const win = getWindow();
            const btn = win
              ? await dialog.showMessageBox(win, {
                  type: 'warning',
                  title: 'Extended range',
                  message: `Apply "${profile.name}" with extended power/temperature limits?`,
                  detail: 'This goes beyond Intel\'s standard limit for the GPU. Whether the card accepts it depends on the card and driver (the Acer BiFrost profile used 300 W).',
                  buttons: ['Cancel', 'Apply'],
                  defaultId: 0,
                  cancelId: 0,
                })
              : await dialog.showMessageBox({
                  type: 'warning',
                  title: 'Extended range',
                  message: `Apply "${profile.name}" with extended power/temperature limits?`,
                  detail: 'This goes beyond Intel\'s standard limit for the GPU. Whether the card accepts it depends on the card and driver (the Acer BiFrost profile used 300 W).',
                  buttons: ['Cancel', 'Apply'],
                  defaultId: 0,
                  cancelId: 0,
                });
            if (btn.response !== 1) {
              if (trayRef && !trayRef.isDestroyed()) {
                trayRef.displayBalloon({ title: 'Arc Power', content: `Arc Power: profile '${profile.name}' not applied — extended range needs confirmation` });
              }
              return;
            }
          }
          // Explicit user action: skips the ocOnBoot gate (like the
          // renderer's Load button) but keeps the waiver gates. The balloon
          // only claims "defaults restored" when a restore actually ran
          // (M2b review F1) — gate refusals get a reason-specific message.
          const out = await applyProfile({ backend, store, profileId: settings.activeProfileId, oldIgcl, applyRunner });
          if (!out.applied && trayRef && !trayRef.isDestroyed()) {
            let name = 'unknown';
            try {
              const ps = await store.loadProfiles();
              const p = ps.find((x) => x.id === settings.activeProfileId);
              if (p) name = p.name;
            } catch { /* best effort name */ }
            const content = trayBalloonForOutcome(out, name);
            if (content) trayRef.displayBalloon({ title: 'Arc Power', content });
          }
        } catch (err) {
          console.error(`[tray] apply active profile failed: ${err.message}`);
          if (trayRef && !trayRef.isDestroyed()) {
            trayRef.displayBalloon({ title: 'Arc Power', content: `Arc Power: profile apply failed — ${err.message}` });
          }
        }
      },
      onQuit: () => app.quit(),
    });
  };
  const tray = createTray({ tray: Tray, nativeImage, Menu, template: await menuTemplate() });
  trayRef = tray;
  // Rebuild the menu when the active profile changes (M2b-B calls this via
  // the window; for now the boot-time state is enough).
  tray.rebuildMenu = async () => { tray.setContextMenu(Menu.buildFromTemplate(await menuTemplate())); };
  return tray;
}

async function main() {
  // --- M2C-C apply-worker mode (`--apply-worker <req> <out>`): ------------
  // hidden (no window, no tray), never re-elevates, exits after writing the
  // result file. Runs the SAME routed instant-apply core as the UI path.
  if (workerReqFile) {
    if (!workerOutFile) {
      console.error('--apply-worker requires <reqFile> <outFile>');
      app.exit(1);
      return;
    }
    // M2C-C S1: the extended-capability probe is constructed BEFORE the
    // backend and injected — the worker's getCapabilities (its clamp ranges)
    // must report the same extended ranges the UI path does.
    const workerOldIgcl = new OldIgcl();
    const code = await runApplyWorker({
      reqPath: workerReqFile,
      outPath: workerOutFile,
      backend: createBackend({
        kind: 'igcl',
        igcl: { extended: { isCapable: () => workerOldIgcl.isCapable() } },
      }),
      oldIgcl: workerOldIgcl,
      log: (s) => console.log(`[apply-worker] ${s}`),
    });
    app.exit(code);
    return;
  }

  if (headless) {
    // M2C-C S1: the smoke path is a real-backend path too — same probe wiring
    // as the app/worker so its caps match the product path. The bundled
    // 2023-runtime probe degrades safely here: a missing/unloadable DLL makes
    // OldIgcl.isCapable() return false (cached), so the smoke's caps stay in
    // the standard range and every health line still runs — the smoke never
    // fails on the probe alone.
    const smokeOldIgcl = mock ? null : new OldIgcl();
    const backend = createBackend({
      kind: mock ? 'mock' : 'igcl',
      igcl: {
        allowAutoWaiver: true, // smoke/tests only (plan §9 M1 waiver clause)
        extended: smokeOldIgcl ? { isCapable: () => smokeOldIgcl.isCapable() } : undefined,
      },
      mock: {},
    });
    try {
      const { lines } = await runSmoke(backend);
      console.log('\nSMOKE OK — ' + lines.filter((l) => l.startsWith('[health]')).length + ' health line(s), see above for the full sequence.');
      app.exit(0);
    } catch (err) {
      console.error(`\nSMOKE FAILED: ${err.message}`);
      app.exit(1);
    }
    return;
  }

  await app.whenReady();
  // --ui-verify runs against MockBackend; the env knobs act as OVERLAYS on
  // the featureset base (mock/featuresets/*.json, RID_MOCK_FEATURESET):
  //   - the ui-verify DEFAULT variant opts into the EDITABLE fan fixture so
  //     the fan editor flow stays fully testable (the a770 featureset base
  //     is the real read-only card); RID_MOCK_FAN_READONLY=1 flips it to the
  //     exact A770 read-only fixture (a hasFan:false featureset always stays
  //     fan-less regardless of the overlay);
  //   - RID_MOCK_OFFGRID_FREQ_MHZ makes the mock report a freq offset off the
  //     1 MHz grid (verifies the off-grid driver readout);
  //   - RID_MOCK_EXTENDED_RANGES / RID_MOCK_EXTENDED_FAIL are session knobs
  //     on top of the featureset extendedRanges flag (a770 carries it
  //     natively).
  const mockOpts = {};
  if (uiVerify) {
    mockOpts.fanCanControl = process.env.RID_MOCK_FAN_READONLY !== '1';
  }
  if (uiVerify && process.env.RID_MOCK_OFFGRID_FREQ_MHZ !== undefined) {
    mockOpts.offGridFreqMhz = Number(process.env.RID_MOCK_OFFGRID_FREQ_MHZ);
  }
  if (uiVerify && process.env.RID_MOCK_EXTENDED_RANGES === '1') mockOpts.extendedRanges = true;
  if (uiVerify && process.env.RID_MOCK_EXTENDED_FAIL === '1') mockOpts.extendedFail = true;
  // M2C-C S1: the real bundled-2023-runtime adapter is constructed BEFORE
  // the backend (mock mode leaves it null — the mock adapter wraps the
  // backend instead). The backend's extended probe consults it lazily
  // (isCapable runs on the first caps query).
  const realOldIgcl = mock ? null : new OldIgcl();
  const backend = createBackend({
    kind: mock ? 'mock' : 'igcl',
    igcl: realOldIgcl
      ? { extended: { isCapable: () => realOldIgcl.isCapable() } }
      : {},
    mock: mockOpts,
  });
  // M2C-C: the bundled 2023 IGCL runtime adapter (extended-range writes).
  // Mock mode (incl. --ui-verify) uses the mock adapter — the real DLL is
  // never loaded there. In the real path the OLD runtime is probed lazily
  // (isCapable runs on the first extended write or caps query) and both
  // runtimes can coexist in one process (probe-verified, §8c). S1: the real
  // adapter is constructed BEFORE the backend so the backend's extended
  // probe (above) can consult it — the extended ranges are wired into
  // getCapabilities on hardware, never dead code.
  const oldIgcl = mock ? createMockOldIgcl(backend) : realOldIgcl;
  // M2C-C elevation probe: real detection in the product path; ui-verify
  // knobs let the mock report elevated (RID_MOCK_ELEVATED=1) so the
  // elevated-in-app UI state is verifiable without elevation. Declared HERE
  // (before the applyRunner block below) — the runner's deps evaluate this
  // identifier eagerly, so any later declaration would be a TDZ crash on the
  // real product path (step-5 S1).
  const isElevated = mock
    ? () => process.env.RID_MOCK_ELEVATED === '1'
    : isElevatedReal;
  // M2C-C: the elevation-aware apply runner. The product path (non-mock)
  // delegates applies to the elevated self-worker when not elevated; mock
  // mode applies in-process (applyRunner null) — ui-verify's worker-apply
  // toast variant injects a FAKE runner (never spawns anything).
  let applyRunner = null;
  if (!mock) {
    applyRunner = createApplyRunner({
      isElevated,
      execPath: process.execPath,
      // Dev mode (`electron .`): process.execPath is electron.exe — the
      // worker spawn must pass the app path along. Packaged EXEs ignore it.
      appPath: process.defaultApp ? app.getAppPath() : null,
      inProcess: {
        apply: async ({ deviceId, settings }) => executeApply({ backend, oldIgcl, deviceId, settings }),
        waiverAccept: async (deviceId) => { await backend.setWaiverAccepted(deviceId); },
        reset: async (deviceId) => {
          await backend.resetToDefaults(deviceId);
          const state = await backend.getCurrentSettings(deviceId);
          return { state };
        },
      },
      log: (s) => console.log(s),
    });
  } else if (uiVerify && process.env.RID_MOCK_WORKER_APPLY === '1') {
    // Dev-only: report the worker-apply path (elevation toast UX) while
    // still applying in-process — never spawns a worker in mock mode.
    applyRunner = {
      needsWorker: () => true,
      apply: async ({ deviceId, settings }) => executeApply({ backend, oldIgcl, deviceId, settings }),
      waiverAccept: async (deviceId) => { await backend.setWaiverAccepted(deviceId); },
      reset: async (deviceId) => {
        await backend.resetToDefaults(deviceId);
        return { ok: true, state: await backend.getCurrentSettings(deviceId) };
      },
    };
  }
  const store = new ProfileStore();
  // Run-key adapter: the real one writes HKCU only on an explicit user click
  // (startup-set IPC); mock mode (incl. --ui-verify) never touches the
  // registry.
  const startup = mock ? createMockStartup() : createStartup();
  // Driver-date adapter: real reg.exe query in the product path; mock mode
  // (incl. --ui-verify) returns the fixture date and never spawns reg.exe.
  const driverInfo = mock ? createMockDriverInfo() : createDriverInfo();
  // M3-A/M3-B registry-catalog + registry-apply adapters (Tweaks page):
  // real read-only reg.exe queries + elevated reg.exe writes in the product
  // path; mock mode (incl. --ui-verify) returns the fixture states and the
  // mock apply flips the SAME in-memory state (never spawns, never
  // elevates). The two mock adapters share one mock registry state so the
  // post-apply state refresh honestly reflects the "written" values.
  const mockRegistryState = mock ? createMockRegistryState() : null;
  const registryCatalog = mock ? createMockRegistryCatalog(REGISTRY_CATALOG, { state: mockRegistryState }) : createRegistryCatalog();
  // ui-verify knobs: RID_MOCK_REGAPPLY_FAIL='<entryId>:<action>' simulates a
  // mid-way reg failure (clamped to the action's last step, so single-step
  // actions still exercise a step-1 failure); RID_MOCK_REGAPPLY_CANCEL=1
  // simulates a UAC decline for the mpo entry; RID_MOCK_REGAPPLY_DELAY_MS
  // adds simulated elevation latency so the in-flight disabled button state
  // can be asserted — all exercise the honest partial/cancel/in-flight UI
  // paths.
  const regApplyFail = process.env.RID_MOCK_REGAPPLY_FAIL;
  const regApplyDelay = Number(process.env.RID_MOCK_REGAPPLY_DELAY_MS);
  const registryApply = mock
    ? createMockRegistryApply(REGISTRY_CATALOG, {
        state: mockRegistryState,
        failAt: regApplyFail
          ? (() => {
              const [entryId, action] = regApplyFail.split(':');
              return { entryId, action, step: 1 };
            })()
          : null,
        canceledActions: process.env.RID_MOCK_REGAPPLY_CANCEL === '1' ? new Set(['mpo']) : new Set(),
        delayMs: regApplyDelay > 0 ? regApplyDelay : 0,
      })
    : createRegistryApply();
  // FPS adapter: mock mode reports unavailable (never loads koffi/PresentMon);
  // the product path starts the real client lazily on the first fps-poll.
  // On this machine the real client degrades to unavailable too (no
  // PresentMon service) — both modes show 'FPS unavailable'. The mock counts
  // polls so --ui-verify can assert the Monitoring page stops polling on
  // navigation away (M2b review F4).
  let fpsPolls = 0;
  const presentmon = mock
    ? { poll: async () => { fpsPolls += 1; return null; } }
    : createPresentmonAdapter();

  let teardown = null;
  app.on('before-quit', () => {
    void teardown?.().catch(() => {});
    void backend.close().catch(() => {});
    void oldIgcl?.close?.().catch(() => {});
  });

  // Boot-time health + waiver seeding (shared by the window path and the
  // apply-on-startup path).
  const bootBackend = async () => {
    try {
      await backend.init();
    } catch {
      // health() reports the init error; the window stays up degraded.
    }
    try { await seedWaiverState(backend, store); } catch (err) {
      console.log(`[boot] waiver seeding skipped: ${err.message}`);
    }
  };

  // --- apply-on-startup (`--apply-profile <id>`): no window, tray only ----
  if (applyProfileId && !uiVerify) {
    await bootBackend();
    // M2b review F2: the flow creates exactly ONE tray (it keeps the app
    // alive in this tray-only mode) and reuses it for the failure balloon.
    // M2C-C: the boot task runs with /rl highest (elevated) so applies are
    // in-process here (applyRunner stays null — a manual non-elevated run
    // fails honestly per control instead of prompting).
    const bootOldIgcl = mock ? createMockOldIgcl(backend) : new OldIgcl();
    await runApplyOnStartup({
      backend,
      store,
      profileId: applyProfileId,
      oldIgcl: bootOldIgcl,
      setupTray: () => setupTray({ getWindow: () => null, backend, store, oldIgcl: bootOldIgcl, applyRunner: null }),
      log: (s) => console.log(s),
    });
    return;
  }

  const win = createWindow();
  // M2D: the mock-featureset IPC surface exists ONLY in mock mode — real
  // mode has no such channel (the renderer's dropdown never renders either).
  const mockCtl = mock
    ? {
        listFeaturesets: () => backend.listFeaturesets(),
        setFeatureset: (id) => backend.setFeatureset(id),
      }
    : null;
  // Whitelisted IPC + telemetry ownership; the renderer drives everything.
  // --ui-verify never creates a tray, so rebuildTray guards the null ref.
  let trayRebuilds = 0;
  teardown = registerIpc({
    backend,
    store,
    getWindow: () => win,
    startup,
    driverInfo,
    registryCatalog,
    registryApply,
    presentmon,
    oldIgcl,
    applyRunner,
    isElevated,
    mock: mockCtl,
    rebuildTray: async () => {
      try { await trayRef?.rebuildMenu?.(); } catch { /* tray unavailable */ }
      // Dev-only probe: lets --ui-verify assert that profile changes reach
      // the tray rebuild hook without a real tray existing.
      if (uiVerify) trayRebuilds += 1;
    },
  });

  if (uiVerify) {
    // Dev-only end-to-end check against MockBackend (never hardware).
    await backend.init();
    // Seed a persisted waiver acceptance (F1) so the dialog does not re-show
    // across runs that share the settings.json data dir.
    try { await seedWaiverState(backend, store); } catch (err) {
      console.log(`[boot] waiver seeding skipped: ${err.message}`);
    }
    await new Promise((resolve) => {
      if (win.webContents.isLoading()) win.webContents.once('did-finish-load', resolve);
      else resolve();
    });
    // M2D featureset variant: RID_MOCK_FEATURESET=<id> (b580 / pro-b50 /
    // arc-igpu) runs the reduced per-featureset verification flow — the full
    // default flow is pinned to A770 values.
    const fsVariant = process.env.RID_MOCK_FEATURESET;
    if (fsVariant && fsVariant !== 'a770') {
      await runFeaturesetVerify(win, fsVariant);
    } else if (process.env.RID_MOCK_TWEAKS_APPLY === '1') {
      // M3-B tweaks-apply variant: drives the full apply flow (mock adapter,
      // no elevation) — enable/disable/revert round trips, per-step toasts,
      // the partial-failure + UAC-cancel honesty paths.
      await runTweaksApplyVerify(win);
    } else {
      await runUiVerify(win, backend, () => trayRebuilds, () => fpsPolls);
    }
    return;
  }

  await bootBackend();
  const health = await collectHealth(backend);
  console.log(`[health] ${JSON.stringify(health)}`);

  await setupTray({ getWindow: () => win, backend, store, oldIgcl, applyRunner });
}

main().catch((err) => {
  console.error(`FATAL: ${err.message}`);
  app.exit(1);
});
