// Arc Power — M2b system tray.
//
// The menu template + icon helpers are electron-free (unit-testable under
// plain node --test); the electron part (createTray) is a thin assembler.
// The icon is an embedded base64 PNG (32x32 — the M3-C-C "new minimal mark":
// dark rounded square + bold accent-blue "A", generated by
// scripts/make-icon.js; the source asset lives in src/assets/tray-icon.png
// and build/). The tray starts only in the normal app path (never headless);
// Show/Hide toggles the window, "Apply active profile" applies the profile
// currently set in settings (only present when one exists), Quit exits.

export const TRAY_ICON_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACYUlEQVR42sWXT2sTQRjG5xtkkv2T3U2b3c02bWKbZLNKLQgilYABhT2JIlIPnsQWL0LFW4t4Vop4Vc9l8RRvC9489dgvoOfFfoFX3ml2YxM3OzupycKPvJl55nne2T+HIWTsMmzPN2wvMGwvMmwPLolo6OmTtEu3ulS3uqFudeE/gxl0LNyluuWezCF8CGa5oyZ00w1104U5E7Jwzez4mtmBBeFjA4GogXm1z5ihgYBo1XakVdsgwtabrwzR9ZhNytU2iFBp3IC734GBtagPKS+3QATvxYekAaxFfUh5eQNE6B3/ShrAWtSHqEsbkJf1R6+T8BgcE/Ei6tI65GX7y2my8/hO4JiIV+4GnN6TZNetp28Z8X+cy92AUrkCedg6DFhY/9sZ6KvXGVjjGM7l9SNKpQm8OL2dv168n9DdO2JgPboLO5DHkyhGE3i59urTxMs3DmryeBLZaAAP2som9Afnt3r78ym4e0cXwDH2aAZnTMvrS2S9ATw0H+4nu6zdfjwxj2PxPGp5fYmsrwEP8XPG31k04xBJW4Us6veejXb3YD9Vh3OxDtfweHM1cPPjD2Z6Z/A7U4sa1OIazgbqMA2jdSvZVWf3PWTpURPrcW2WnpTKdZjG5sFxYog1BkxjXJ/lT0rlFUhDtb3M7z4L9JiWQUqqA2l0nr+buQH0mJZBiqoTFVUH/sXa/ZfMYBbQI80fs0lRqQVFpQYLIsAG/AU2cH5Uo4odUsWGORMmJyMq25TK9gmVLZgPmGVfPB9S2aJUtsI5NIAZNPWUXJBMvyCZQUEyo4JkwiURDT0njud/AEVKAn1jrdsDAAAAAElFTkSuQmCC';

export const TRAY_LABEL_TOGGLE = 'Show / Hide window';
export const TRAY_LABEL_APPLY_PROFILE = 'Apply active profile';
export const TRAY_LABEL_QUIT = 'Quit';
export const TRAY_BALLOON_TITLE = 'Arc Power';
export function trayBalloonProfileFailed(name) {
  return `Arc Power: profile '${name}' failed to apply — defaults restored`;
}

/**
 * M4-D Round-1 F5: the tray toggle's window action. A MINIMIZED window
 * reports isVisible() === true — the old visibility-only toggle would HIDE
 * a minimized window instead of restoring it (a start-minimized session
 * could never be restored from the tray). The minimize case wins: restore
 * first; only a visible, non-minimized window toggles to hidden.
 * @param {{ isMinimized: boolean, isVisible: boolean }} winState
 * @returns {'restore' | 'hide' | 'show'}
 */
export function trayToggleAction({ isMinimized, isVisible }) {
  if (isMinimized) return 'restore';
  return isVisible ? 'hide' : 'show';
}

/** Balloon text for a gate refusal (nothing was applied or restored). */
export function trayBalloonProfileRefused(reason) {
  return `Arc Power: profile not applied — ${reason}`;
}

/**
 * Balloon content for an apply outcome (M2b review F1). The failure balloon
 * claims "defaults restored" ONLY when a restore actually ran
 * (`fallbackApplied !== undefined`); gate refusals get a reason-specific
 * message; a successful apply balloons nothing (returns null).
 * @param {{ applied: boolean, reason: string, fallbackApplied?: boolean }} out
 * @param {string} name
 * @returns {string | null}
 */
export function trayBalloonForOutcome(out, name) {
  if (out.applied) return null;
  if (out.fallbackApplied !== undefined) return trayBalloonProfileFailed(name);
  return trayBalloonProfileRefused(out.reason);
}

/**
 * Decode the embedded icon (pure, no electron): returns the PNG dimensions
 * from the IHDR chunk so tests can pin the icon without a window.
 * @returns {{ width: number, height: number, bytes: number }}
 */
export function decodeTrayIcon() {
  const b64 = TRAY_ICON_DATA_URL.slice(TRAY_ICON_DATA_URL.indexOf(',') + 1);
  const bytes = Buffer.from(b64, 'base64');
  if (bytes.length < 24 || bytes.readUInt32BE(0) !== 0x89504e47) {
    throw new Error('tray icon is not a valid PNG');
  }
  return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20), bytes: bytes.length };
}

/**
 * Pure menu template (electron-free, testable).
 * @param {{
 *   hasActiveProfile: boolean,
 *   onToggle: () => void,
 *   onApplyProfile: () => void,
 *   onQuit: () => void,
 * }} deps
 * @returns {Array<{ label: string, enabled: boolean, click: () => void }>}
 */
export function buildTrayMenuTemplate({ hasActiveProfile, onToggle, onApplyProfile, onQuit }) {
  const items = [
    { label: TRAY_LABEL_TOGGLE, enabled: true, click: onToggle },
  ];
  if (hasActiveProfile) {
    items.push({ label: TRAY_LABEL_APPLY_PROFILE, enabled: true, click: onApplyProfile });
  }
  items.push({ label: TRAY_LABEL_QUIT, enabled: true, click: onQuit });
  return items;
}

/**
 * Electron assembler: build the Tray with the embedded icon + the template.
 * Only ever called from the normal app path (never headless). The returned
 * tray is kept alive by the caller (module-level reference).
 * @param {{
 *   tray: import('electron').Tray,
 *   nativeImage: import('electron').NativeImage,
 *   Menu: typeof import('electron').Menu,
 *   template: ReturnType<typeof buildTrayMenuTemplate>,
 * }} deps — electron types injected so the module stays importable in tests
 * @returns {import('electron').Tray}
 */
export function createTray({ tray: Tray, nativeImage, Menu, template }) {
  const icon = nativeImage.createFromDataURL(TRAY_ICON_DATA_URL);
  const t = new Tray(icon);
  t.setToolTip('Arc Power');
  t.setContextMenu(Menu.buildFromTemplate(template));
  return t;
}
