// Arc Power — M2b system tray.
//
// The menu template + icon helpers are electron-free (unit-testable under
// plain node --test); the electron part (createTray) is a thin assembler.
// The icon is an embedded base64 PNG (32x32 blue "AP" logo, generated by
// scripts/make-icon.js — M2C-B B6; the source assets live in
// src/assets/tray-icon.png and build/). The tray starts only in the normal
// app path (never headless); Show/Hide toggles the window,
// "Apply active profile" applies the profile currently set in settings
// (only present when one exists), Quit exits.

export const TRAY_ICON_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAADkklEQVR42r2X+09TZxzG3z+hv8DEuEXNzDRuYZk3IkiX+MOMWeYv/qKbWhMTkRA3gibTTK0JLJvEAJsJM8QLOkSRFEjcxNaIMkLUjlRFroLCoNYrh7a2tNL2Me8xh5z31jZOfZJPQt7v8zzfXg4HDiEmWZvjFmtz3G5tSXisLQm8ZTx6d3PcQmTKd0zb8h0xLd8RwztGo7uY5XmNUduqxijeJ3Snvjz3XNiS2zCl5TZMgeerpgjavXEMagmU3XwJmed/oNHdZGV9yL6yPgQZf92fhllbWqeg8r4hdpJTF/Tk1AUhIxhNMC+g4t8IVF5eha6w0mvCQ1ac9kPGpgti6eBEDCo/rx3OF0qvGbL85ARk1PdGINO6Rr/Ur1KXbxoFrUGo9pClx59BxsDzmLTQ3h6U+lNp1+WANEeW1DwBz9dnnyuL2kYikGVSKRBN4MtTT4Uc+eLoI/CUdwaSlsky6ehAm1/Ikc+rveBxe6NJi4ovTgiZdPSHOyDkSPaRMZjJq0ld1tIXAp9LR4f+0YQc+ey3UZj5yZX6ggpE4uBz6WjNCa+QI59WPoCZ5p5gWmXr67xMjtfW8z7w3TLI4sPDMEPfXTo61TXJ5HjZGrzgu2WQReWDMChqeih81MZsz9/sld73OAJzlteWs+PMXAVZ+Es/DGrd7B3NcWdyZras8p6wZHX18Myc1+Yz/8HcrYJ88nMvDMYnX7J/UBrHYJ7fGA0x8zLXo5kZr01/jjBZFWRB6V1QvqkZEkqMmUGp08fMXQOBmRmv704/EPIyyMcH74BS2sr+/jv7/TBmBtaqPvGu+Otdfcbr29phIS+DzD/gAaXXF2YKdjeNwpiZGdPYu2RVmw8bT4jXBz2T5XnIvH1dyC67JRSsOtwNOjOzyzEivACVNhwbFPIyyNy9buSV32bCPQ9DoOcGa3/v0c/SFfXSjLlDBfnoxxugVLjG9bA/HMOaqm4Y5yXnh/GmolmjRwX5cHcnVGyr7Ve/S+8LdA75dejPKtGOZDvInJIOz5ySDshouPlYKKRnOaVuwUvPVH5VP91NZhe322cXt0PF/qYh+MOv/z3/4cwAknkp1PP6q5zWsyn8dpL1/TVL1s6rWtbOq1Cx3H4dW2u6kcxjhnppJoVPo7v1p6NZRVdsHxRdwfuE7mSeDzMLL9syC11aZqEL7xiN7pI+IWcUOC0ZBU57xvZLnoztl/CW8ejdBU7m8fwV3WG/KCun0ZIAAAAASUVORK5CYII=';

export const TRAY_LABEL_TOGGLE = 'Show / Hide window';
export const TRAY_LABEL_APPLY_PROFILE = 'Apply active profile';
export const TRAY_LABEL_QUIT = 'Quit';
export const TRAY_BALLOON_TITLE = 'Arc Power';
export function trayBalloonProfileFailed(name) {
  return `Arc Power: profile '${name}' failed to apply — defaults restored`;
}

/** Balloon text for a gate refusal (nothing was applied or restored). */
export function trayBalloonProfileRefused(reason) {
  return `Arc Power: profile not applied — ${reason}`;
}

/**
 * Balloon content for an apply outcome (M2b review F1). The failure balloon
 * claims "defaults restored" ONLY when a restore actually ran
 * (`fallbackApplied !== undefined`); gate refusals get a reason-specific
 * message; a successful apply balloons nothing (returns null).
 * @param {{ applied: boolean, reason: string, fallbackApplied?: boolean }} out
 * @param {string} name
 * @returns {string | null}
 */
export function trayBalloonForOutcome(out, name) {
  if (out.applied) return null;
  if (out.fallbackApplied !== undefined) return trayBalloonProfileFailed(name);
  return trayBalloonProfileRefused(out.reason);
}

/**
 * Decode the embedded icon (pure, no electron): returns the PNG dimensions
 * from the IHDR chunk so tests can pin the icon without a window.
 * @returns {{ width: number, height: number, bytes: number }}
 */
export function decodeTrayIcon() {
  const b64 = TRAY_ICON_DATA_URL.slice(TRAY_ICON_DATA_URL.indexOf(',') + 1);
  const bytes = Buffer.from(b64, 'base64');
  if (bytes.length < 24 || bytes.readUInt32BE(0) !== 0x89504e47) {
    throw new Error('tray icon is not a valid PNG');
  }
  return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20), bytes: bytes.length };
}

/**
 * Pure menu template (electron-free, testable).
 * @param {{
 *   hasActiveProfile: boolean,
 *   onToggle: () => void,
 *   onApplyProfile: () => void,
 *   onQuit: () => void,
 * }} deps
 * @returns {Array<{ label: string, enabled: boolean, click: () => void }>}
 */
export function buildTrayMenuTemplate({ hasActiveProfile, onToggle, onApplyProfile, onQuit }) {
  const items = [
    { label: TRAY_LABEL_TOGGLE, enabled: true, click: onToggle },
  ];
  if (hasActiveProfile) {
    items.push({ label: TRAY_LABEL_APPLY_PROFILE, enabled: true, click: onApplyProfile });
  }
  items.push({ label: TRAY_LABEL_QUIT, enabled: true, click: onQuit });
  return items;
}

/**
 * Electron assembler: build the Tray with the embedded icon + the template.
 * Only ever called from the normal app path (never headless). The returned
 * tray is kept alive by the caller (module-level reference).
 * @param {{
 *   tray: import('electron').Tray,
 *   nativeImage: import('electron').NativeImage,
 *   Menu: typeof import('electron').Menu,
 *   template: ReturnType<typeof buildTrayMenuTemplate>,
 * }} deps — electron types injected so the module stays importable in tests
 * @returns {import('electron').Tray}
 */
export function createTray({ tray: Tray, nativeImage, Menu, template }) {
  const icon = nativeImage.createFromDataURL(TRAY_ICON_DATA_URL);
  const t = new Tray(icon);
  t.setToolTip('Arc Power');
  t.setContextMenu(Menu.buildFromTemplate(template));
  return t;
}
